language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: finbarr
  password:
    secure: PBaS4/28XIwwTvAkyblemeWDHo8S6vdqFTl/dm7GBPliUVqHP27YlhRa25OfiGzV8JtCi9u+/k8WP0wEKqAgZjaWFy0kS6kkVtGaPfNgg/K2UUly+DwYf2I40ph93U8+vqmZp0Lp6DqKUQ2O/QVrcT6zzzUq9VQGspf00zuxq8oQkE4odImSuKbTqNCqutBZj4ReTvcrKpW1+xP1C2AVUz+LqdffXCkd2F5D0c91+jbfpUWynuwPcoH1FHh3LBbX3LwirWs0p90MyP26MoWGmjedz4jhdxJUIUosR9DWeDE6AKeBW0pz6WIU5Xm7eqOCUpW82x62MXs4H2satYcaUM8zDZeCMWGoRJ6BihakQnweLrWbga5qQrxL7sbG211eqbHR8r4t43TOwqJBRijXC4ouiSiq5dZsbTv1RMpbC1NWko8mAL9H5DiFKn2uhd0Y+xnyfY+Mkp8Hb2CADF90Plom7PxwscCPpu2PueotTj5qN6NaYLRWX0h59VLnWwb61U5U9DHs5AYYWLL2kucV/wJBUByee5q4lILTSbUz5V4GxJzn9aBytSn+brz5VCOSbaiaeU0ihGH4akhXFCeOrw80JvBPPN5gRBzhDInRgqzyUlHJ53QqP2WRmzqOkbhcOfjLwvNEk03RuPByYPQOHInW0rOI0ZCvAST/Qsi2Y6Q=
  on:
    tags: true
    repo: fbradyirl/openwebifpy
    python: 3.6
